const ENV = {
  API_BASE_URL: process.env.REACT_APP_API_BASE_URL,
  OPEN_API_BASE_URL: process.env.REACT_APP_OPEN_API_BASE_URL,
  WEBSITE_URL: process.env.REACT_APP_WEBSITE_URL,
  NEXT_PUBLIC_RAPIDAPI_HOST: process.env.NEXT_PUBLIC_RAPIDAPI_HOST,
  NEXT_PUBLIC_RAPIDAPI_KEY: process.env.NEXT_PUBLIC_RAPIDAPI_KEY,
  CORE_API_BASE_URL: process.env.CORE_API_BASE_URL,
};
 

export {
  ENV
};
